name: Github Pages

on:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - master
      - github-action-migrate
jobs:
  Archiving:
    runs-on: ubuntu-latest

    env:
      #GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY_GITHUB_PAGE }}
      DEPLOY_USER_NAME: Deploy-GitHub-Action
      DEPLOY_USER_EMAIL: github_action@pdis.tw

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - uses: ./.github/actions/archiving-images
      - uses: ./.github/actions/commit-if-change
        with:
          commit_user_name: $DEPLOY_USER_NAME
          commit_user_email: $DEPLOY_USER_EMAIL
          custom_commit_message: >
            Auto archive image

            Archive and Modify follow file:
      - name: Push to remote
        run: |
          git pull --rebase
          git push

  Translating:
    runs-on: ubuntu-latest

    needs: Archiving

    env:
      DEPLOY_USER_NAME: Deploy-GitHub-Action
      DEPLOY_USER_EMAIL: github_action@pdis.tw
      ENCRYPT_KEY: ${{ secrets.ENCRYPTED_2FB15357D122_KEY }}
      ENCRYPT_IV: ${{ secrets.ENCRYPTED_2FB15357D122_IV }}
      GOOGLE_APPLICATION_CREDENTIALS: ./.github/actions/auto-translation/GCP.json
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Decode Google Cloud transation API Key
        run: |
          openssl aes-256-cbc -K $ENCRYPT_KEY -iv $ENCRYPT_IV -in GCP.json.enc -out ./.github/actions/auto-translation/GCP.json -d
      - uses: actions/setup-node@v2
        with:
          node-version: "8"
      - uses: ./.github/actions/auto-translation
      - uses: ./.github/actions/commit-if-change
        with:
          commit_user_name: $DEPLOY_USER_NAME
          commit_user_email: $DEPLOY_USER_EMAIL
          custom_commit_message: >
            Auto translate

            Generate follow file:
      - name: Push to remote
        run: |
          git pull --rebase
          git push

  Deploying:
    runs-on: ubuntu-latest

    needs: [Archiving, Translating]

    strategy:
      matrix:
        ruby: ["2.6"]

    env:
      #GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY_GITHUB_PAGE }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      DEPLOY_USER_NAME: Deploy-GitHub-Action
      DEPLOY_USER_EMAIL: github_action@pdis.tw
      PUBLISH_DIR: ./_site
      ENCRYPT_KEY: ${{ secrets.ENCRYPTED_2FB15357D122_KEY }}
      ENCRYPT_IV: ${{ secrets.ENCRYPTED_2FB15357D122_IV }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          ref: ${{ github.ref }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Building page
        run: |
          bundle install
          bundle exec jekyll build
          find _site -name '*html' -exec sed -i 's/tw\/zh-TW\/assets/tw\/assets/g' {} +
          find _site -name '*html' -exec sed -i 's/tw\/en\/assets/tw\/assets/g' {} +
      - name: Deploy to GitHub Page
        uses: actions-js/push@v1.3
        with:
          github_token: $GITHUB_TOKEN
          author_email: $DEPLOY_USER_EMAIL
          author_name: DEPLOY_USER_NAME
          message: "Deploy $GITHUB_SHA to GitHub Pages"
          branch: gh-pages
          force: true
          directory: $PUBLISH_DIR
          
        #run: |
        #  cd $PUBLISH_DIR
        #  git init
        #  git config --local user.email $DEPLOY_USER_EMAIL
        #  git config --local user.name $DEPLOY_USER_NAME
        #  git remote add origin https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
        #  git checkout -b gh-pages
        #  git add --all
        #  git commit -m "Deploy $GITHUB_SHA to GitHub Pages"
        #  git push origin gh-pages -f
