name: Scheduled Reubuild

on:
  workflow_dispatch:
jobs:
  Deploying:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: ["2.6"]

    env:
      GITHUB_TOKEN: ${{ secrets.DEPLOY_KEY_GITHUB_PAGE }}
      DEPLOY_USER_NAME: Deploy-GitHub-Action
      DEPLOY_USER_EMAIL: targee@cosa.org.tw
      PUBLISH_DIR: ./_site
      ENCRYPT_KEY: ${{ secrets.ENCRYPTED_2FB15357D122_KEY }}
      ENCRYPT_IV: ${{ secrets.ENCRYPTED_2FB15357D122_IV }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          ref: ${{ github.ref }}
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Building page
        run: |
          bundle install
          bundle exec jekyll build
          find _site -name '*html' -exec sed -i 's/tw\/zh-TW\/assets/tw\/assets/g' {} +
          find _site -name '*html' -exec sed -i 's/tw\/en\/assets/tw\/assets/g' {} +
      - name: Deploy to GitHub Page
        run: |
          cd $PUBLISH_DIR
          git init
          git config --local user.email $DEPLOY_USER_EMAIL
          git config --local user.name $DEPLOY_USER_NAME
          git remote add origin https://$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git
          git checkout -b gh-pages
          git add --all
          git commit -m "Deploy $GITHUB_SHA to GitHub Pages"
          git push origin gh-pages -f
